### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: Wrapped code seems to be truncated. Expected length of 11155 characters but got only 4018.

### ISSUE THREAD

**Issue by saidazimabdukhamidov** [Trivadis/plsql-unwrapper-sqldev#2]
![image](https://user-images.githubusercontent.com/34978419/110448981-890a0980-80e3-11eb-9993-7a2b99a001dd.png)

**Comment by PhilippSalvisberg** [comment]
This does not look like a screenshot within SQL Developer. That's an unsupported usage. Therefore I close this issue.

**Comment by saidazimabdukhamidov** [comment]
I am using your .jar file in my java code. And this error is appearing,
when I insert more than 4096 characters.
