### ISSUE TITLE
Unable to install in Oracle Linux

### ISSUE THREAD

**Issue by tejasomina** [Trivadis/plsql-unwrapper-sqldev#3]
Latest version 1.0.0.1878 is not getting installed in Oracle Linux.
I tried installing the tool both directly from the downloaded pack and from update center. 
It asks to restart SQL developer and after that, I neither see the unwrapper in 'Preferences' nor I see the option to wnrap when I right-click on a wrapped PL/SQL package.

SQL Developer Version 20.4.0.379 Build 379.2205
OS: Oracle Linux 5.4.17-2102.203.6.el7uek.x86_64
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)

**Comment by PhilippSalvisberg** [comment]
Can you install any other extension? E.g. those listed [here](https://github.com/PhilippSalvisberg/sqldev-update#considered-sql-developer-extensions). 

If not then I suspect that the user running SQLDev does not have the rights to modify and extend the installation.

In this case I suggest to run the installation via `sudo`. See also https://github.com/oddgen/oddgen/issues/38 . 

`sudo` is not needed for subsequent starts (after a successful installation).

**Comment by PhilippSalvisberg** [comment]
Closed due to inactivity, feel free to open another issue if the problem persists.
